window.APP_CONFIG = {
  SUPABASE_URL: "https://sbfpcsdnpnjbjvorydpr.supabase.co",
  SUPABASE_PUBLISHABLE_KEY: "sb_publishable_VGX2Wnp1KGMYwLtYTM-Gbw_6fosyXfC",
  DEFAULT_FIELD_DURATION_MINUTES: 60,
  OPENING_HOUR: 9,
  PAID_FROM_HOUR: 19,
  CLOSING_HOUR: 22,
  CONTACT_PHONE_DISPLAY: "328 673 9425",
  CONTACT_PHONE_LINK: "+393286739425"
};
